export const HOME= '/';
export const LOGIN= '/login';
export const CONTACT ='/contactus';
export const ABOUTUS='/about';
export const FAQ='/faq';
export const CAREERS='/careers';
export const PRIVACY='/privacy';
export const GUIDES='/guides';
export const VIDEOTIPS='/videotips';    
